apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame
  labels:
    kind: webserver
    project: learn_k8
    owner: ward
spec:
  template:
      metadata:
        name: test-nginx
        labels: 
          project: learn_k8
          type: webserver
      spec:
        containers:
          - name: webserver
            image: nginx
          - name: startup
            image: busybox
            envFrom:
              - configMapRef:
                  name: configmap
            command: ["sh",  "-c", 'echo "Value from configmap:" $APP_COLOR && sleep 3600']
                
  replicas: 2
  selector:
    matchLabels:
      type: webserver
