apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job

spec:
  completions: 3
  parallelism: 3
  template:
    metadata:
      name: 
        math-add-pod
    spec:
      containers: 
        - name: math-add-container
          image: ubuntu
          command: ["expr", "3", "+", "4"]
      restartPolicy: Never