apiVersion: v1
kind: Pod
metadata:
  name: busybox-ls
  labels: 
    project: learn_k8
spec:
  containers:
    - name: webserver
      image: busybox
      volumeMounts:
      - name: secrets-volume
        mountPath: "/secrets"
        readOnly: true
      command: ["sh", "-c", 'ls /var/run/secrets/kubernetes.io/serviceaccount && sleep 60']
  volumes:
    - name: configmap-volume
      configMap:
        name: configmap
    - name: secrets-volume
      secret:
        secretName: app-secret
  serviceAccount: dashboard-sa